{
 "title": "Quilibrium Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": "label_values(origin_prometheus)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   { "name": "quil_price", "query": { "query": "" } },
   { "name": "peers", "label": "peers", "query": { "query": "label_values(peer_id)" } }
  ]
 },
 "panels": [
  { "title": "Quilibrium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "My nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) ({__name__=~\".+\",job=\"node\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "root_is_not_array": true
     },
     "pagination_mode": "none",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://dashboard-api.quilibrium.com/live-peers",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api.livecoinwatch.com/coins/single",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n    \"currency\": \"USD\",\n    \"code\": \"WQUIL\",\n    \"meta\": true\n  }",
      "headers": [
       {
        "key": "x-api-key",
        "value": "c1a3670b-fa4d-438f-8a93-19a204f10c82"
       }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Price chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "parser": "uql",
     "root_selector": "history",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"history\"\n| extend \"date\"=format_datetime(\"date\",'YYYY-MM-DD') ",
     "url": "https://api.livecoinwatch.com/coins/single/history",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n\t\"currency\": \"USD\",\n\t\"code\": \"WQUIL\",\n\t\"start\": \"${__from}\",\n\t\"end\": \"${__to}\"\n}",
      "headers": [
       {
        "key": "x-api-key",
        "value": "c1a3670b-fa4d-438f-8a93-19a204f10c82"
       }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Number of nodes by cores",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "cores", "text": "", "type": "number" }
     ],
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "parser": "backend",
     "root_selector": "$.*",
     "source": "url",
     "summarizeBy": "cores",
     "summarizeExpression": "count(cores)",
     "type": "json",
     "uql": "parse-json",
     "url": "https://dashboard-api.quilibrium.com/network-info",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Current price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$quil_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ATH",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api.livecoinwatch.com/coins/single",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n    \"currency\": \"USD\",\n    \"code\": \"WQUIL\",\n    \"meta\": true\n  }",
      "headers": [
       {
        "key": "x-api-key",
        "value": "c1a3670b-fa4d-438f-8a93-19a204f10c82"
       }
      ],
      "method": "POST"
     }
    }
   ]
  },
  { "title": "Rewards post v1.4.19", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Balance (Q)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24 * 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quilibrium",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "last_over_time(quilibrium_unclaimed_balance [1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(quilibrium_max_frame [1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24 * 30",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(quilibrium_unclaimed_balance [1h]) * $quil_price",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24 * $quil_price",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24 * 30 * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance ($)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quilibrium_unclaimed_balance{}[10m]) * 6 * 24 * 30) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance (Q) (total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Rewards pre v1.4.19", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Balance (Q)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 226 }
   ]
  },
  {
   "title": "Rewards Pre 1.4.19",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "reward", "text": "", "type": "number" },
      { "selector": "peerId", "text": "", "type": "string" }
     ],
     "computed_columns": [
      { "selector": "reward * ${quil_price}", "text": "Pre-1.4.18 ($)", "type": "string" }
     ],
     "filterExpression": "peerId in (${peers:singlequote})",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://quilibrium.com/rewards/pre-1.4.18.json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "reward", "text": "", "type": "number" },
      { "selector": "peerId", "text": "", "type": "string" }
     ],
     "computed_columns": [
      { "selector": "reward * ${quil_price}", "text": "Post-1.4.18 ($)", "type": "string" }
     ],
     "filterExpression": "peerId in (${peers:singlequote})",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://quilibrium.com/rewards/post-1.4.18.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Balance ($)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 226 }
   ]
  },
  {
   "title": "Nodes overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server resource overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"node\"})by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_uname_info{job=\"node\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node\", mode='system'}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"node\"} / (node_memory_MemTotal_bytes{job=\"node\"})))* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"node\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"node\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=\"node\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=\"node\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"node\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"node\",}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"node\",}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node_hwmon_temp_celsius{job=\"node\",chip=~\"pci0000:00_0000:00:18_3|platform_coretemp_0\",sensor=\"temp1\"}[$interval]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(quilibrium_unclaimed_balance{hostname=\"$node\"}[10m]) * 6 * 24 * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / month",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(quilibrium_unclaimed_balance{hostname=\"$node\"}[10m]) * 6 * 24 * 30 * $quil_price ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node details【$show_hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Balance (Q)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance{hostname=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(quilibrium_unclaimed_balance{hostname=\"$node\"}[10m]) * 6 * 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / month",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(quilibrium_unclaimed_balance{hostname=\"$node\"}[10m]) * 6 * 24 * 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max frame",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(quilibrium_max_frame{hostname=\"$node\"} [1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance (Q)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "quilibrium_unclaimed_balance{ hostname=\"$node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Balance ($)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance{hostname=\"$node\"}) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 51 } },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "quilibrium_peer_store_count{hostname=\"$node\"}",
     "legendFormat": "peer store"
    },
    {
     "expr": "quilibrium_network_peer_count{hostname=\"$node\"}",
     "legendFormat": "network peers"
    }
   ]
  },
  {
   "title": "Peers sync per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by (peer_id)( count_over_time({unit=\"quilibrium.service\", hostname=\"$node\"} |= `syncing target` [1h]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "【$show_hostname】：Disk space used",
   "type": "table",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Internet traffic per hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\"}",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk Space Used%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  }
 ]
}