version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 8081:3000
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=AvAcalhinh0!
    volumes:
      - ./dashboards/quilibrium-dashboard.json:/var/lib/grafana/dashboards/quilibrium-dashboard.json
#      - ./dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json:/var/lib/grafana/dashboards/grafana-dashboard-cloud-impacts.template.json
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
  grafana_loki:
    image: grafana/loki
    container_name: grafana_loki
    ports:
      -  3100:3100
    volumes:
      - loki_data:/loki
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    #ports:
    #  - 9100:9100
    command: '--path.rootfs=/host --collector.systemd --collector.processes'
    uts: host
    pid: host
    network_mode: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
volumes:
  prom_data:
  loki_data:
  grafana_data:
